# Export Qahf and Qh
- This script is used to export anthropogenic heat flux (Qahf) and sensible heat flux (Qh);
- Simulations: BASE, SENS;

In [1]:
import xarray as xr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [9]:
path = '/mnt/iusers01/fatpou01/sees01/a16404ys/scratch/'
archive = '/Projects/archive/0project2/0sensitivity/'
sites = ['AU-Pre','US-Bal','US-Wes']
file_date = ['2004-05-18', '2006-12-05', '2012-12-24']
start_date = ['2004-05-18T00:00:00', '2006-12-05T02:00:00','2012-12-24T00:00:00']
end_date = ['2004-05-25T23:30:00', '2006-12-12T01:00:00', '2012-12-31T23:30:00']
psites = ["AU-Preston","US-Baltimore","US-WestPhoenix"]
output_dir = '/mnt/iusers01/fatpou01/sees01/a16404ys/scratch/output_analysis/project2/sp_sensitivity/urban_heat/'
hour = ['01800', '07200', '01800']

In [7]:
dfs1 = []
result_df1 = pd.DataFrame()
for i in range(3):
    for j in range(9):
        if j<8:
            ds = xr.open_dataset(path + archive + sites[i] + '_sen_temp/' + sites[i] + '_sen_temp.clm2.h0.' + file_date[i]+'-' + hour[i] + '_' + str(7-j) + '.nc')
        else:
            ds = xr.open_dataset(path + '/Projects/archive/0project2/0sp/' + sites[i] + '_sen_base/lnd/hist/' + sites[i] + '_sen_base.clm2.h0.' + file_date[i]+'-' + hour[i]+ '.nc')
        ds['time']=ds['time'].dt.round('min')
        ds['time']=ds['time'].dt.ceil('min')
        #urban_heat = ds['URBAN_HEAT']
        urban_heat = ds['WASTEHEAT']+ ds['URBAN_HEAT']
        
        df = urban_heat.to_dataframe(name='urban_heat').reset_index()
        #df['hour']=(df.time.dt.hour + zone[i]) % 24
        df['hour']=(df.time.dt.hour) % 24
        df['minute']=df.time.dt.minute
        df['index']=j
        df['site'] = sites[i]
        df['date'] = urban_heat.time.values
        df['time'] = df['hour'].astype(str).str.zfill(2) + ':' + df['minute'].astype(str).str.zfill(2)
        dfs1.append(df)

# Concatenate DataFrames for all sites
result_df1 = pd.concat(dfs1, ignore_index=True)
result_df1.to_csv(output_dir + 'ahf.csv', index = False)
result_df1

,time,lndgrid,urban_heat,hour,minute,index,site,date
0,00:30,0,0.333320,0,30,0,AU-Pre,2004-05-18 00:30:00
1,01:00,0,0.000000,1,0,0,AU-Pre,2004-05-18 01:00:00
2,01:30,0,0.000000,1,30,0,AU-Pre,2004-05-18 01:30:00
3,02:00,0,0.000000,2,0,0,AU-Pre,2004-05-18 02:00:00
4,02:30,0,0.000000,2,30,0,AU-Pre,2004-05-18 02:30:00
...,...,...,...,...,...,...,...,...
7555,22:00,0,3.111179,22,0,8,US-Wes,2012-12-30 22:00:00
7556,22:30,0,2.404568,22,30,8,US-Wes,2012-12-30 22:30:00
7557,23:00,0,2.058502,23,0,8,US-Wes,2012-12-30 23:00:00
7558,23:30,0,2.114214,23,30,8,US-Wes,2012-12-30 23:30:00
7559,00:00,0,2.044480,0,0,8,US-Wes,2012-12-31 00:00:00

In [8]:
dfs2 = []
result_df2 = pd.DataFrame()
for i in range(3):
    for j in range(9):
        if j<8:
            ds = xr.open_dataset(path + archive + sites[i] + '_sen_temp/' + sites[i] + '_sen_temp.clm2.h0.' + file_date[i]+'-' + hour[i] + '_' + str(7-j) + '.nc')
        else:
            ds = xr.open_dataset(path + '/Projects/archive/0project2/0sp/' + sites[i] + '_sen_base/lnd/hist/' + sites[i] + '_sen_base.clm2.h0.' + file_date[i]+'-' + hour[i] + '.nc')
        ds['time']=ds['time'].dt.round('min')
        ds['time']=ds['time'].dt.ceil('min')
        #urban_heat = ds['URBAN_HEAT']
        urban_heat = ds['FSH_U']
        
        df = urban_heat.to_dataframe(name='urban_heat').reset_index()
        #df['hour']=(df.time.dt.hour + zone[i]) % 24
        df['hour']=(df.time.dt.hour) % 24
        df['minute']=df.time.dt.minute
        df['index']=j
        df['site'] = sites[i]
        df['date'] = urban_heat.time.values
        df['time'] = df['hour'].astype(str).str.zfill(2) + ':' + df['minute'].astype(str).str.zfill(2)
        dfs2.append(df)
        
result_df2 = pd.concat(dfs2, ignore_index=True)
result_df2.to_csv(output_dir + 'qh.csv', index = False)
result_df2

,time,lndgrid,urban_heat,hour,minute,index,site,date
0,00:30,0,-3.032928,0,30,0,AU-Pre,2004-05-18 00:30:00
1,01:00,0,1.376907,1,0,0,AU-Pre,2004-05-18 01:00:00
2,01:30,0,53.016338,1,30,0,AU-Pre,2004-05-18 01:30:00
3,02:00,0,4.985089,2,0,0,AU-Pre,2004-05-18 02:00:00
4,02:30,0,71.220757,2,30,0,AU-Pre,2004-05-18 02:30:00
...,...,...,...,...,...,...,...,...
7555,22:00,0,51.665443,22,0,8,US-Wes,2012-12-30 22:00:00
7556,22:30,0,42.123882,22,30,8,US-Wes,2012-12-30 22:30:00
7557,23:00,0,50.734264,23,0,8,US-Wes,2012-12-30 23:00:00
7558,23:30,0,36.560940,23,30,8,US-Wes,2012-12-30 23:30:00
7559,00:00,0,29.687134,0,0,8,US-Wes,2012-12-31 00:00:00